global:
  imagePullPolicy: Always
  vault:
    host: ""
    vaultToken: ""

frontend:
  replicas: 1
  revisionHistoryLimit: 15
  strategy:
    type: Recreate
  service:
    port: 80
  ingress:
    host: front-alexanderpanov.2sem.students-projects.ru
    path: /
    pathType: Prefix
    tls:
      secretName: 2sem-students-projects-wildcard-secret
  containerPort: 80
  image:
    repository: panovast/sausage-frontend
    tag: latest
  resources:
    requests:
      memory: "128Mi"
      cpu: "100m"
    limits:
      memory: "128Mi"
      cpu: "250m"
  nginxConf: nginx.conf

backend:
  annotations:
    path: /actuator/prometheus
    port: "8080"
    scrape: "true"
  env:
    reportPath: /logs/reports
    logPath: /logs
  service:
    port: 8080
  revisionHistoryLimit: 15
  replicas: 1
  strategy:
  type: RollingUpdate
  rollingUpdate:
    maxUnavailable: 1
    maxSurge: 2
  image:
    repository: panovast/sausage-backend
    tag: latest
  imagePullPolicy: Always
  resources:
    requests:
      memory: "256Mi"
      cpu: "200m"
    limits:
      memory: "256Mi"
      cpu: "500m"
  containerPort: 8080
  livenessProbe:
    httpGet:
      path: /actuator/health
      port: 8080
    initialDelaySeconds: 90
    periodSeconds: 15
    timeoutSeconds: 5
  hpa:
    enabled: true
    minReplicas: 1
    maxReplicas: 3
    metrics:
      - type: Resource
        resource:
          name: cpu
          target:
            type: Utilization
            averageUtilization: 80
      - type: Resource
        resource:
          name: memory
          target:
            type: Utilization
            averageUtilization: 80
  vpa:
    enabled: true
    updatePolicy:
      updateMode: "Off"
    resourcePolicy:
      containerPolicies:
        - containerName: "*"
          minAllowed:
            cpu: "50m"
            memory: "128Mi"
          maxAllowed:
            cpu: "200m"
            memory: "256Mi"
          controlledResources: ["cpu", "memory"]

backend-report:
  replicas: 1
  image:
    repository: panovast/sausage-backend-report
    tag: latest
  imagePullPolicy: Always
  revisionHistoryLimit: 15
  containerPort: 8080
  strategy:
    type: Recreate
  service:
    port: 8080
  resources:
    requests:
      memory: "128Mi"
      cpu: "50m"
    limits:
      memory: "128Mi"
      cpu: "100m"
  livenessProbe:
    httpGet:
      path: /api/v1/health
      port: 8080
    initialDelaySeconds: 15
    periodSeconds: 10
  hpa:
    enabled: true
    minReplicas: 1
    maxReplicas: 3
    metrics:
      - type: Resource
        resource:
          name: cpu
          target:
            type: Utilization
            averageUtilization: 80
      - type: Resource
        resource:
          name: memory
          target:
            type: Utilization
            averageUtilization: 80
  vpa:
    enabled: false
    updatePolicy:
      updateMode: "Auto"
    resourcePolicy:
      containerPolicies:
        - containerName: "*"
          minAllowed:
            cpu: "50m"
            memory: "128Mi"
          maxAllowed:
            cpu: "100m"
            memory: "256Mi"
          controlledResources: ["cpu", "memory"]

infra:
  postgresql:
    persistence:
      enabled: true
      size: 1Gi
    resources:
      requests:
        memory: "128Mi"
        cpu: "100m"
      limits:
        memory: "256Mi"
        cpu: "200m"
    containerPort: 5432
  mongodb:
    containerPort: 27017
