apiVersion: batch/v1
kind: Job
metadata:
  name: mongodb-init
  labels:
    app.kubernetes.io/name: mongodb-init
    app.kubernetes.io/instance: "{{ .Release.Name }}"
    app.kubernetes.io/version: "{{ .Chart.AppVersion }}"
    app.kubernetes.io/managed-by: "{{ .Release.Service }}"
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app.kubernetes.io/component: infra
    app.kubernetes.io/part-of: sausage-store
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "5"
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mongodb-init
        app.kubernetes.io/instance: "{{ .Release.Name }}"
    spec:
      containers:
        - name: mongodb-init
          image: mongo:7.0
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "200m"
              memory: "256Mi"
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongodb-secrets
                  key: MONGO_INITDB_ROOT_USERNAME
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb-secrets
                  key: MONGO_INITDB_ROOT_PASSWORD
            - name: MONGO_DB_NAME
              valueFrom:
                secretKeyRef:
                  name: mongodb-secrets
                  key: MONGO_DB_NAME
            - name: MONGO_DB_USER
              valueFrom:
                secretKeyRef:
                  name: mongodb-secrets
                  key: MONGO_DB_USER
            - name: MONGO_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb-secrets
                  key: MONGO_DB_PASSWORD
          command:
            - sh
            - -c
            - |
              # Wait for mongo
              until mongosh --host mongodb --port 27017 -u "$MONGO_INITDB_ROOT_USERNAME" -p "$MONGO_INITDB_ROOT_PASSWORD" --authenticationDatabase admin --eval "db.adminCommand('ping')" ; do
                echo "Waiting for mongo to be ready..."
                sleep 2
              done
              mongosh --host mongodb --port 27017 \
                -u "$MONGO_INITDB_ROOT_USERNAME" \
                -p "$MONGO_INITDB_ROOT_PASSWORD" \
                --authenticationDatabase admin \
                --eval "
                  db = db.getSiblingDB('$MONGO_DB_NAME');
                  if (db.getUser('$MONGO_DB_USER') == null) {
                    db.createUser({
                      user: '$MONGO_DB_USER',
                      pwd: '$MONGO_DB_PASSWORD',
                      roles: [
                        { role: 'readWrite', db: '$MONGO_DB_NAME' },
                      ]
                    });}
                "
      restartPolicy: OnFailure
