apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secrets
type: Opaque
stringData:
  MONGO_INITDB_ROOT_USERNAME: root
  MONGO_INITDB_ROOT_PASSWORD: rootpassword
  MONGO_DB_NAME: reports
  MONGO_DB_USER: reports_user
  MONGO_DB_PASSWORD: reports_password