---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-front-service
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}-{{ .Chart.Name }}-front-service
    app.kubernetes.io/instance: "{{ .Release.Name }}"
    app.kubernetes.io/version: "{{ .Chart.AppVersion }}"
    app.kubernetes.io/managed-by: "{{ .Release.Service }}"
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
spec:
  type: ClusterIP
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.containerPort | default .Values.service.port }}
      protocol: TCP
  selector:
    app: {{ .Release.Name }}-{{ .Chart.Name }}